import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import CreateItem from "../components/CreateItem";
import Rankedlist from "../components/Rankedlist";
export default function Home() {
  return (
    <div className={styles.container}>
      <div className="text-center">
      <Head>
        <title>Quadratic Voting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p className="mt-1 text-4xl font-extrabold text-white sm:text-5xl sm:tracking-tight lg:text-6xl">
        Enter an event {"📝"}
      </p>
      <h1>Before CreateItem</h1>
      <CreateItem />
      {/* <Rankedlist />  */}
      </div>
      
    </div>
  );
}

