import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import CreateItem from "../components/CreateItem";
import Rankedlist from "../components/Rankedlist";
import ShowEvents from "../components/ShowEvents";
import { useState, useEffect } from "react";
import { useMoralis, useWeb3Contract } from "react-moralis";

export default function Home() {
  const { chainId: chainIdHex, web3, isWeb3Enabled, account } = useMoralis();
  // const [isClickedEvent, setIsClickedEvent] = useState(false);
  // function clickBack() {
  //   setIsClickedEvent(false);
  // };

  // function clickRanklist() {
  //   setIsClickedEvent(true);
  //   console.log("click");
  // };

  return (
    <div>
    {isWeb3Enabled && (
      <div className={styles.container}>
        <Head>
          <title>Quadratic Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <ShowEvents />
        {/* End of Page */}
    </div>
    )}
    {!isWeb3Enabled && (
      <div>
        <Head>
          <title>Quadratic Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div>
          <h1>Welcome!</h1>
          <h2>connect ur wallet first!</h2>{" "}
        </div>
      </div>
    )}
    </div>
  );
}

//   return (
//     <div>
//     {!isClickedEvent && (
//       <div className={styles.container}>
//         <Head>
//           <title>Quadratic Voting</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <Header />
//         <button onClick={clickRanklist}>To Rankedlist</button>
//         <ShowEvents />
//         {/* End of Page */}
//     </div>
//     )}
//     {isClickedEvent && (
//       <div className={styles.container}>
//         <Head>
//           <title>Quadratic Voting</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <Header />
//         <button onClick={clickBack}>Back</button>
//         <CreateItem />
//         <Rankedlist />
//       </div>
//     )}
//     </div>
//   );
// }
//
