import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import CreateItem from "../components/CreateItem";
import Rankedlist from "../components/Rankedlist";
import ShowEvents from "../components/ShowEvents";
import { useState, useEffect } from "react";
export default function Home() {
  const [isClickedEvent, setIsClickedEvent] = useState(false);
  function clickBack() {
    setIsClickedEvent(false);
  };
  function clickRanklist() {
    setIsClickedEvent(true);
  };

  return (
    <div>
    {!isClickedEvent && (
      <div className={styles.container}>
        <Head>
          <title>Quadratic Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <button onClick={clickRanklist}>To Rankedlist</button>
        {/* <CreateItem /> */}
        <ShowEvents />
        {/* <Rankedlist /> */}
        {/* End of Page */}
    </div>
    )}
    {isClickedEvent && (
      <div className={styles.container}>
        <Head>
          <title>Quadratic Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <button onClick={clickBack}>Back</button>
        <CreateItem />
        <Rankedlist />
      </div>
    )}
    </div>
  );
}
//
